### PR TITLE
Clear initial element value

### PR DESCRIPTION
**Pull request by kendaleiv**
- Clear initial element value to avoid any potential confusion.
- Version `1.0.0-alpha.2`.

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
Won't this breakdown model binding from the server?

1. Load page
2. Submit form
3. Validation error -> Redirect to form
4. Now field is empty

Is this correct?

**Comment by kendaleiv** [comment]
Behind the scenes, the `name` property is moved onto an `input[type="hidden"]` that tracks the *real* value for form submission purposes.

https://github.com/ritterim/age-picker/blob/d6c4fde7188d2d7987e03501938b81804d4bbbba/test/age-picker.js#L140-L148 is a test showing how `<input data-age-picker />` has the value set on the `input[type="hidden"]`.

**Comment by khalidabuhakmeh** [comment]
But when you reload a page, that field will still be empty correct?

**Comment by kendaleiv** [comment]
If the form `<input data-age-picker />` has an initial `value` set I assume it will put things in the state of the first page load after a reload.

**Comment by kendaleiv** [comment]
If the form `<input data-age-picker />` has an initial `value` set I assume it will put things in the state of the first page load after a reload.

**Pull request merged**
